kind: Deployment
apiVersion: apps/v1
metadata:
  name: security-sys-ldap-nonprod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-sys-ldap-nonprod
      targetEnv: dev
  template:
    metadata:
      labels:
        app: security-sys-ldap-nonprod
        targetEnv: dev
    spec:
      containers:
      - name: ldap
        image: osixia/openldap:1.2.4
        volumeMounts:
        - name: ldap-data
          mountPath: /var/lib/ldap
        - name: ldap-config
          mountPath: /etc/ldap/slapd.d
        ports:
        - containerPort: 389
          name: openldap
        env:
        - name: LDAP_ORGANISATION
          value: "Thoughtbend"
        - name: LDAP_DOMAIN
          value: "thoughtbend.com"
        - name: LDAP_ADMIN_PASSWORD
          value: "myp4ss0wrd"

      volumes:
      - name: ldap-data
#        hostPath:
#          path: "/data/ldap-data/db"
        persistentVolumeClaim:
          claimName: security-ldap-data-pv-claim
      - name: ldap-config
#        hostPath:
#          path: "/data/ldap-data/config"
        persistentVolumeClaim:
            claimName: security-ldap-config-pv-claim
#      - name: ldap-certs
#        hostPath:
#          path: "/Users/mikenolan/container_home/ldap-data/certs"