apiVersion: v1
kind: Service
metadata:
  labels:
    app: security-sys-ldap-nonprod
  name: security-sys-ldap-nonprod-svc
spec:
  type: NodePort
  ports:
  - port: 389
    nodePort: 30389
    protocol: TCP
  selector:
    app: security-sys-ldap-nonprod
    targetEnv: dev