kind: PersistentVolume
apiVersion: v1
metadata:
  name: security-db-pv-volume
  labels:
    type: local
    vname: security-db-pv-volume
    env: nonprod
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/secdb-mysql"
    type: DirectoryOrCreate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: security-db-pv-claim
spec:
  storageClassName: standard
  selector:
    matchLabels:
      vname: security-db-pv-volume
      env: nonprod
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi