kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: security-ldap-data-pv-claim
spec:
#  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: security-ldap-config-pv-claim
spec:
#  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi