kind: PersistentVolume
apiVersion: v1
metadata:
  name: security-http-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /container-home/nginx/security-sys-api-2  
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: security-http-pv-claim
#spec:
#  storageClassName: manual
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 2Gi