apiVersion: v1
kind: ReplicationController
metadata:
  name: security-db-nonprod-rc
spec:
  replicas: 1
  selector:
    app: security-db-nonprod
  template:
    metadata:
      labels:
        app: security-db-nonprod
    spec:
      containers:
      - name: security-db-nonprod-pod
        image: mysql:{{.Values.mysql.imageVersion}}
        args:
        - "--ignore-db-dir=lost+found" 
        volumeMounts: 
        - name: security-db-volume
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: {{.Values.rootpass}}
      volumes:
      - name: security-db-volume
        persistentVolumeClaim:
          claimName: security-db-pv-claim