apiVersion: v1
kind: ReplicationController
metadata:
  name: security-sys-http-nonprod-rc
spec:
  replicas: 1
  selector:
    app: security-sys-http-nonprod
  template:
    metadata:
      labels:
        app: security-sys-http-nonprod
    spec:
      containers:
      - name: security-sys-http-nonprod-pod
        image: nginx
        ports:
        - containerPort: 443
        volumeMounts: 
        - mountPath: /etc/nginx/thoughtbend.crt
          subPath: thoughtbend.crt
          name: tls-cert-files
          readOnly: true
        - mountPath: /etc/nginx/thoughtbend.key
          subPath: thoughtbend.key
          name: tls-cert-files
          readOnly: true
        - mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          name: default-conf-file
      volumes:
      - name: default-conf-file
        configMap:
          name: sec-sys-http-nonprod-default-conf
      - name: tls-cert-files
        secret:
          secretName: security-http-tls-cert